-- Import Expert Patterns from expert_patterns.json
-- This script will import the expert patterns as case studies
-- Note: Due to the large size of the JSON file, this is a sample import
-- For full import, use the TypeScript script: import_expert_patterns.ts

-- Sample import of first 20 patterns
INSERT INTO case_studies (id, title, description, device_brand, device_model, device_category, fault_category, fault_description, symptoms, diagnosis, solution, required_tools, required_parts, difficulty_level, estimated_time, success_rate, related_ics, related_faults, status, view_count, helpful_count, metadata) VALUES
(
  gen_random_uuid(),
  'رعشة الشاشة (Screen Flickering)',
  'رعشة في الشاشة أو ظهور خطوط أفقية بعد فترة من التشغيل',
  'General',
  'Various Laptop Models',
  'Laptop',
  'display',
  'Screen Flickering or horizontal lines after operation',
  ARRAY['رعشة في الشاشة', 'خطوط أفقية'],
  'Hardware Design Flaw in LG screens',
  'العطل غالباً Hardware Design Flaw في شاشات LG المستخدمة. تقنياً، يتم فحص دائرة الـ Backlight Booster ومكوناتها مثل PU401. إذا استمرت المشكلة بعد تغيير الشاشة، يتم مراجعة الـ EMI Filters بجانب كنكتور الشاشة J4001 والتأكد من عدم وجود تمليح.',
  ARRAY['مقياس ديود', 'سخان الهواء الساخن'],
  ARRAY['PU401'],
  'intermediate',
  30,
  85,
  ARRAY['PU401'],
  ARRAY['SCREEN_FLICKER'],
  'verified',
  0,
  0,
  '{"source": "expert_patterns.json", "pattern_index": 0}'::jsonb
),
(
  gen_random_uuid(),
  'الجهاز لا يعمل تماماً (No Power - Dead)',
  'الجهاز لا يعمل تماماً - No Power Dead',
  'General',
  'Various Laptop Models',
  'Laptop',
  'power',
  'Device completely dead - no power',
  ARRAY['الجهاز لا يعمل', 'ميت تماماً'],
  'Missing standby voltages or charging circuit failure',
  'الخوارزمية: 1. افحص جهد الدخل 19V (أو 12V) عند المقاومة PR1 (Current Sensor). 2. تأكد من وجود جهد Standby (3.3V / 5V) على الملفات PL301 و PL302. 3. إذا غاب جهد الـ 3.3V، افحص خرج منظم الجهد LDO في الـ IC المسؤول (PU301). 4. افحص إشارة التشغيل (Power Button Signal) على الـ IO (IT8586E) عند الرجل المسؤولة (عادة PWR_SW#). 5. تأكد من سلامة كريستالة الـ RTC (32.768 KHz).',
  ARRAY['مقياس ديود', 'مقياس التيستر', 'سخان الهواء الساخن'],
  ARRAY['PR1', 'PL301', 'PL302', 'PU301', 'IT8586E'],
  'advanced',
  45,
  80,
  ARRAY['PU301', 'IT8586E'],
  ARRAY['NO_POWER', 'STANDBY_VOLTAGE_MISSING'],
  'verified',
  0,
  0,
  '{"source": "expert_patterns.json", "pattern_index": 1}'::jsonb
),
(
  gen_random_uuid(),
  'الشاشة الزرقاء المتكررة (BSOD)',
  'الشاشة الزرقاء المتكررة - Blue Screen of Death',
  'General',
  'Various Laptop Models',
  'Laptop',
  'system',
  'Blue Screen of Death (BSOD)',
  ARRAY['شاشة زرقاء', 'BSOD', 'رستر'],
  'Memory or CPU thermal issues',
  'الخوارزمية: 1. افحص استقرار جهد الرامات وجهد الـ VCCSA. 2. اختبر الرامات ببرنامج MemTest86. 3. افحص حرارة المعالج ودرجة جفاف المعجون الحراري. 4. إذا كان الكود (WHEA_UNCORRECTABLE_ERROR)، افحص مكثفات التصفية تحت المعالج (Tantalum Capacitors).',
  ARRAY['MemTest86', 'مقياس حرارة', 'معجون حراري'],
  ARRAY[],
  'intermediate',
  20,
  75,
  ARRAY[],
  ARRAY['BSOD', 'MEMORY_ERROR', 'CPU_THERMAL'],
  'verified',
  0,
  0,
  '{"source": "expert_patterns.json", "pattern_index": 2}'::jsonb
),
(
  gen_random_uuid(),
  'الواي فاي لا يعمل (Wi-Fi Not Detected)',
  'الواي فاي لا يعمل - Wi-Fi Not Detected',
  'General',
  'Various Laptop Models',
  'Laptop',
  'wireless',
  'Wi-Fi card not detected',
  ARRAY['واي فاي لا يعمل', 'لا يتعرف على الواي فاي'],
  'Power or PCIe lane issue with Wi-Fi module',
  'الخوارزمية: 1. افحص جهد الـ 3.3V على سوكيت الـ Mini PCIe أو M.2. 2. تأكد من إشارة الـ WLAN_Disable القادمة من الـ IO (يجب أن تكون High). 3. افحص خطوط الـ PCIe Lane بين الكارت والـ PCH. 4. استبدل الكارت للتأكد من عدم وجود عطل هاردوير في الكارت نفسه.',
  ARRAY['مقياس ديود', 'مقياس فولت'],
  ARRAY[],
  'beginner',
  15,
  85,
  ARRAY[],
  ARRAY['WIFI_NOT_DETECTED', 'WIFI_POWER_ISSUE'],
  'verified',
  0,
  0,
  '{"source": "expert_patterns.json", "pattern_index": 3}'::jsonb
),
(
  gen_random_uuid(),
  'قصر صريح على خط الـ 19V (Hard Short)',
  'قصر صريح على خط 19 فولت - Hard Short',
  'General',
  'Various Laptop Models',
  'Laptop',
  'power',
  'Hard short on 19V line',
  ARRAY['قصر صريح', 'شورت 19 فولت', 'سحب كامل'],
  'Short circuit on main power rail',
  'الخوارزمية: 1. استخدم طريقة الحقن (Voltage Injection) بجهد منخفض (1V) وأمبير عالٍ. 2. استخدم الكاميرا الحرارية لتحديد المكون التالف (غالباً مكثف سيراميكي PC). 3. افحص موسفتات الـ High-Side في دوائر الـ Buck Converter.',
  ARRAY['Power Supply', 'كاميرا حرارية', 'سخان الهواء الساخن'],
  ARRAY[],
  'expert',
  60,
  70,
  ARRAY[],
  ARRAY['HARD_SHORT_19V', 'SHORT_CIRCUIT'],
  'verified',
  0,
  0,
  '{"source": "expert_patterns.json", "pattern_index": 4}'::jsonb
);

-- Note: This is a sample of 5 patterns. The full JSON file contains 200+ patterns.
-- Use the TypeScript script for full import.

SELECT 'Sample import completed! Use TypeScript script for full import.' as message;
